name: Email Bot - Cleaning Routine

on:
  workflow_dispatch:

jobs:
  run-cleaning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install google-auth google-auth-oauthlib google-api-python-client openpyxl

    - name: Create credentials.json
      run: |
        mkdir -p resources
        echo '${{ secrets.CREDENTIALS_JSON }}' > resources/credentials.json

    - name: Create token.json
      run: |
        mkdir -p resources
        echo '${{ secrets.TOKEN_JSON }}' > resources/token.json

    - name: Validate JSON files
      run: |
        python -m json.tool resources/credentials.json
        python -m json.tool resources/token.json

    - name: Run CLEANING routine
      run: |
        python main.py cleaning