name: Run Email Bot

on:
  schedule:
    - cron: '*/10 * * * *'   # Runs every 10 minutes
  workflow_dispatch:         # Also allow manual triggering

jobs:
  run-email-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade google-auth google-auth-oauthlib google-api-python-client openpyxl terminal-notifier

    - name: Create resources directory
      run: mkdir -p resources

    - name: Create credentials.json from secret
      env:
        GMAIL_CREDENTIALS: ${{ secrets.GMAIL_CREDENTIALS }}
      run: |
        echo "$GMAIL_CREDENTIALS" | base64 --decode > resources/credentials.json

    # Optional: Create token.json from secret if you stored it.
    - name: Create token.json from secret (if available)
      if: ${{ secrets.GMAIL_TOKEN != '' }}
      env:
        GMAIL_TOKEN: ${{ secrets.GMAIL_TOKEN }}
      run: |
        echo "$GMAIL_TOKEN" | base64 --decode > resources/token.json

    - name: Run Email Bot Script
      run: |
        python main.py
